import streamlit as st
import pandas as pd
import os

st.set_page_config(page_title='Vehicle Speed Dashboard', layout='wide', page_icon='🚗')

st.title('🚗 Vehicle Speed Estimation Dashboard')
st.caption('Upload a vehicle log CSV generated by main.py to view analytics.')

with st.sidebar:
    st.header('Settings')
    speed_limit = st.slider('Speed Limit (km/h)', 20, 120, 60)
    st.divider()
    uploaded_csv = st.file_uploader('Upload vehicle_log.csv', type=['csv'])

if uploaded_csv:
    df = pd.read_csv(uploaded_csv)
    df = df.dropna(subset=['speed_kmh'])

    violations = df[df['speed_kmh'] > speed_limit]
    safe = df[df['speed_kmh'] <= speed_limit]

    col1, col2, col3, col4 = st.columns(4)
    col1.metric('Total Records', len(df))
    col2.metric('Unique Vehicles', df['track_id'].nunique())
    col3.metric('Violations', len(violations), delta=f"{(len(violations)/len(df)*100):.1f}%")
    col4.metric('Avg Speed', f"{df['speed_kmh'].mean():.1f} km/h")

    st.divider()

    col_a, col_b = st.columns(2)

    with col_a:
        st.subheader('Speed Distribution')
        st.bar_chart(df['speed_kmh'].value_counts().sort_index())

    with col_b:
        st.subheader('Vehicles by Class')
        if 'class_name' in df.columns:
            st.bar_chart(df['class_name'].value_counts())

    st.subheader('Violation Log')
    if len(violations) > 0:
        st.dataframe(violations[['frame_id', 'timestamp', 'track_id', 'class_name', 'speed_kmh']].sort_values('speed_kmh', ascending=False), use_container_width=True)
    else:
        st.success('No violations detected!')

    st.subheader('Full Log')
    st.dataframe(df, use_container_width=True)
else:
    st.info('Upload a CSV file from the sidebar to get started.')
